name: 'Package Application'
description: 'MVN or DOCKER Package application'
on:
  workflow_dispatch:
    inputs:
      PROJECT_KEY:
        description: 'Project key'
        required: false
        type: string
        default: 'spring-petclinic-ms'
      BUILD_PROFILE:
        description: 'Build profile MVN or DOCKER'
        required: false
        type: choice
        default: 'MVN'
        options:
          - MVN
          - DOCKER
      APPLICATION_KEY:
        description: 'Application key'
        required: true
        type: string
      BUILD_NAME:
        description: 'Build Name'
        required: true
        type: string
        default: 'spring-petclinic-${{inputs.APPLICATION_KEY}}'
      BUILD_ID:
        description: 'Build Id'
        required: true
        type: string
      RT_REPO_VIRTUAL:
        description: 'App Virtual repo name'
        required: true
        type: string
      JF_NAME:
        description: 'JFrog SaaS HostName'
        required: false
        type: string
        default: 'psazuse'
env:
  JAVA_DISTRIBUTION: 'temurin'
  JAVA_VERSION: '25'
  DOCKER_BUILDX_PLATFORMS: 'linux/amd64,linux/arm64'
jobs:
  build-mvn:
    runs-on: ubuntu-latest

  using: 'composite'
  steps:
    - name: "Setup JFrog CLI"
      uses: jfrog/setup-jfrog-cli@v5  # https://github.com/jfrog/setup-jfrog-cli
      id: setup-cli
      env:
        JF_URL: "https://${{inputs.JF_NAME}}.jfrog.io"
        JF_PROJECT: "${{inputs.PROJECT_KEY}}"
        JFROG_CLI_LOG_LEVEL: "DEBUG"
        JFROG_CLI_RELEASES_REPO: 'https://${{inputs.JF_NAME}}.jfrog.io/artifactory/${{inputs.RT_REPO_VIRTUAL}}' 
        JFROG_CLI_EXTRACTORS_REMOTE: 'https://${{inputs.JF_NAME}}.jfrog.io/artifactory/${{inputs.RT_REPO_VIRTUAL}}'
        with:
          version: latest  #2.71.0
          oidc-provider-name: ${{vars.JF_OIDC_PROVIDER_NAME}}
          disable-job-summary: "FALSE"

    - name: "Clone VCS"
      uses: actions/checkout@v6 # ref: https://github.com/actions/checkout

    - name: "setUp JDK provider = ${{env.JAVA_DISTRIBUTION}} with ver = ${{env.JAVA_VERSION}}"
      uses: actions/setup-java@v5  # ref https://github.com/actions/setup-java
      with:
          distribution: ${{env.JAVA_DISTRIBUTION}} # temurin
          java-version: ${{env.JAVA_VERSION}}  # 25

    - name: "JFCli Configure"
      run: |
        jf mvnc --repo-resolve-releases ${{inputs.RT_REPO_VIRTUAL}} --repo-resolve-snapshots ${{inputs.RT_REPO_VIRTUAL}} --repo-deploy-releases ${{inputs.RT_REPO_VIRTUAL}} --repo-deploy-snapshots ${{inputs.RT_REPO_VIRTUAL}}   


    - name: "MVN Package application"
      if: ${{ inputs.buildProfile == 'MVN' }}
      run: |
        jf mvn clean install surefire-report:report -pl spring-petclinic-${{inputs.APPLICATION_KEY}} -am --build-name=${{inputs.BUILD_NAME}} --build-number=${{inputs.BUILD_ID}} --project="${{inputs.PROJECT_KEY}}" --detailed-summary

    - name: "DOCKER Package application"
      if: ${{ inputs.buildProfile == 'DOCKER' }}
      run: |
        jf mvn clean install surefire-report:report -P buildDocker -Dcontainer.platform="linux/arm64" -pl spring-petclinic-${{inputs.APPLICATION_KEY}} -am --build-name=${{inputs.BUILD_NAME}} --build-number=${{inputs.BUILD_ID}} --project="${{inputs.PROJECT_KEY}}" --detailed-summary

    - name: "Build Info"
      run: |
        jf rt bp ${{inputs.BUILD_NAME}} ${{inputs.BUILD_ID}} --collect-env=true --collect-git-info=true --project="${{inputs.PROJECT_KEY}}" --detailed-summary

    - name: "AppTrust: App Version create"
      env:
        APP_SPEC_JSON: "./jfcli-app-spec.json"
      run: |
        cat > "${{env.APP_SPEC_JSON}}" <<EOF
        {
          "builds": [
            {
              "name": "${{inputs.BUILD_NAME}}",
              "number": "${{inputs.BUILD_ID}}",
              "repository_key": "${{inputs.PROJECT_KEY}}-build-info",
              "include_dependencies": false
            }
          ]
        }
        EOF

        printf "AppTrust app spec file content: ${{env.APP_SPEC_JSON}}"
        cat ${{env.APP_SPEC_JSON}}

        # ref: https://docs.jfrog.com/governance/docs/create-application-version-cli 
        jf apptrust version-create ${{inputs.APPLICATION_KEY}} ${{inputs.BUILD_ID}} --spec="${{env.APP_SPEC_JSON}}" --tag="Package"


