name: "Frogbot Scan"
on: push
permissions:

  contents: read
  security-events: write
  # [Mandatory if using OIDC authentication protocol instead of JF_ACCESS_TOKEN]
  id-token: write
env:
  JF_RT_URL: "https://${{vars.JF_NAME}}.jfrog.io"
  PROJECT_KEY: "spring-petclinic-ms"
jobs:
  scan-repository:
    runs-on: ubuntu-latest
    environment: frogbot
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.head_ref }}

      - uses: jfrog/frogbot@v3  # ref: https://github.com/jfrog/frogbot
        env:
          JF_URL: "${{env.JF_RT_URL}}"
          JF_PROJECT: "${{env.PROJECT_KEY}}"
          JFROG_CLI_LOG_LEVEL: "DEBUG"
          JF_GIT_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          ACTIONS_ALLOW_UNSECURE_NODE_VERSION: true  # Allow secure Node fallback
          JF_WORKING_DIR: "**/src/main/**"
          JF_PATH_EXCLUSIONS: "*git*;*node_modules*;*target*;*venv*;*test*"
        with:
            version: latest #2.71.0
            oidc-provider-name: ${{ vars.JF_OIDC_PROVIDER_NAME }}