name: "AppTrust: Package"

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  actions: read

jobs:
  api-gateway:
    name: "MVN: api-gateway"
    uses: ./.github/workflows/jfcli-commons.yml
    secrets: inherit
    with:
      project_key: "spring-petclinic-ms"
      application_key: "api-gateway"
      build_profile: "MVN"
      build_name: "api-gateway"
      build_id: "ga-${{ github.run_number }}" 
      rt_repo_virtual: "spring-petclinic-ms-api-gateway-virtual"

